# Generated by Django 3.2.7 on 2021-10-02 06:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_newuser_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageConvert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_text', models.CharField(max_length=150)),
                ('converted_text', models.CharField(blank=True, max_length=150)),
                ('input_lan', models.CharField(max_length=150)),
                ('output_lan', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
